### ISSUE TITLE
Browser asking for hi-res version of image

### ISSUE THREAD

**Issue by RobertoRDT** [evt-project/evt-builder#10]
In the latest build (20191207) when using single images with no hi-res counterpart (the *_big.jpg version) both Chrome and Firefox ESR 60 pop up a modal warning saying "There was a problem while loading the hi-res image." which has to be closed to continue viewing the edition. This happens even if the lens, the only functionality requiring a hi-res version of the shown image, is disabled.

**Comment by ChiaraDipi** [comment]
Modal removed!
