### ISSUE TITLE
Insert a graphic space between two steps

### ISSUE THREAD

**Issue by federicaspinelli** [evt-project/evt-builder#18]
Add a blank line between two paragraphs. See this image f.i.:
![immagine](https://user-images.githubusercontent.com/26044952/77431757-736dd800-6ddd-11ea-826d-a8bde6ec17a2.png)

**Comment by gmarozzi** [comment]
Inserting a withe space beetween two <p element, in order to represent the division betwwen two steps

**Comment by RobertoRDT** [comment]
You can have empty lines, numbered or unnumbered, in EVT 1.3 using `<lb/>`, check the manual.

**Comment by federicaspinelli** [comment]
Fixed in EVT 1.3
