### ISSUE TITLE
Manage colors based on the extent of the interventions

### ISSUE THREAD

**Issue by federicaspinelli** [evt-project/evt-builder#22]
The colors used to represent `<add>` and `<del>` could be too deep when used to highlight small scale phenomena, such as the deletion of a dot or the addition of a comma, it would be better to use a lighter shade of the same colors.

**Comment by gmarozzi** [comment]
The colors used to represent <add> and <del> could be too deep when used to hilight small processes, such as the deletion of a . or the addition of a , It could be useful to change the colors used with a lighter shade

**Comment by RobertoRDT** [comment]
Already done in EVT 1.3:

![immagine](https://user-images.githubusercontent.com/16621283/77514731-9fd63280-6e77-11ea-849d-a5b318a3b4f9.png)

**Comment by federicaspinelli** [comment]
Fixed in EVT 1.3
