### ISSUE TITLE
Handling of <titlePage>

### ISSUE THREAD

**Issue by RobertoRDT** [evt-project/evt-builder#7]
At the moment (build 20191206) `<titlePage>` works but it presents two issues:

1. it is shown in the text frame with little to no formatting:

![immagine](https://user-images.githubusercontent.com/16621283/70312155-518f1c00-1813-11ea-9ced-42257b81d8b5.png)

Desired formatting:
- keep the text centering
- handling of `<titlePart type="main">` and `<titlePart type="sub">` identical to `<head type="main"> `and `<head type="sub">`
- converting `<ref>`s targeting URLs in proper hyperlinks
- adding a new line after each sub-element (at the moment only `<docAuthor>` seems to have this)
- possibly a smaller character for the `<docImprint>` element

2. in the **Info** window content of `<titlePart>` is formatted in bold-italic, but it is duplicated.

![immagine](https://user-images.githubusercontent.com/16621283/70312532-21944880-1814-11ea-8a56-763a058a8860.png)

Adding a full `<titlePage>` (instead of a simple one only holding a `<titlePart>`) issues similar to 1. are present, except for the conversion of `<ref>`s to proper hyperlinks:

![immagine](https://user-images.githubusercontent.com/16621283/70312766-91a2ce80-1814-11ea-8207-1c9e4722ece4.png)

**Comment by ChiaraDipi** [comment]
Duplication of text is actually a bug and it'll be fixed as soon as possibile.

Regarding requests about formatting, unfortunately we didn't handle every possible elements inside the `<titlePage>`, but there is always the possibility to add your own XSLT templates and CSS rules.
For example you can add the following template
```
<xsl:template match="tei:docImprint" mode="interp dipl #default">
    <div class="docImprint">
        <xsl:call-template name="dataAttributesFromAttributes"/>
        <xsl:apply-templates mode="#current"/>
    </div>
</xsl:template>
```

And then style the element with a custom CSS rule:
```
.docImprint {
    display: block;
    font-size: 80%;
}
```

**NB:** Thanks to `<xsl:call-template name="dataAttributesFromAttributes"/>` every node attribute will be transformed in a HTML `data-*` attribute and could be used to style with more precision your elements. Don't worry if xslt file doesn't validate with this line

**Comment by ChiaraDipi** [comment]
Support for `<titlePart>` has been added.

**Comment by RobertoRDT** [comment]
I played a little with custom templates and custom CSS, and this is what I got:

![immagine](https://user-images.githubusercontent.com/16621283/70371842-64b7ef80-18d8-11ea-97c1-bd535f6e1ad4.png)

which is not bad, although I don't understand why all text besides the `<titlePart>`s is at 80% dimension while this is only specified for `<docImprint>`; there's also an overlap with `<docAuthor>` being handled elsewhere in the current modules. I'm attaching the custom XSLT and CSS style sheets, we could use these as an example for people wanting to customize the visualization.


[evt_builder-custom-styles.txt](https://github.com/evt-project/evt1/files/3934899/evt_builder-custom-styles.txt)
[evt_builder-custom-templates.txt](https://github.com/evt-project/evt1/files/3934900/evt_builder-custom-templates.txt)
